- 학습시작일 : 2022년 04월 15일 - 16시 36분

# 02-1 데이터 집합 불러오기

## 갭마인더 데이터 집합 불러오기

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/countifs/fork-doit_pandas/master/data/gapminder.tsv', sep='\t')

## 불러온 데이터 집합 살펴보기

In [3]:
print(df.head())

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106

In [4]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [5]:
print(df.shape)

(1704, 6)

In [6]:
len(df)

1704

In [7]:
print(df.columns)

Index(['country', 'continent', 'year', 'lifeExp', 'pop', 'gdpPercap'], dtype='object')

In [8]:
print(df.dtypes)

country       object
continent     object
year           int64
lifeExp      float64
pop            int64
gdpPercap    float64
dtype: object

In [9]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   country    1704 non-null   object
 1   continent  1704 non-null   object
 2   year       1704 non-null   int64
 3   lifeExp    1704 non-null   float64
 4   pop        1704 non-null   int64
 5   gdpPercap  1704 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 80.0+ KB
None

# 02-2 데이터 추출하기

### 열 단위로 데이터 추출하기

In [10]:
country_df = df['country']

In [11]:
print(type(country_df))

<class 'pandas.core.series.Series'>

In [12]:
print(country_df.head())

0    Afghanistan
1    Afghanistan
2    Afghanistan
3    Afghanistan
4    Afghanistan
Name: country, dtype: object

In [13]:
print(country_df.tail())

1699    Zimbabwe
1700    Zimbabwe
1701    Zimbabwe
1702    Zimbabwe
1703    Zimbabwe
Name: country, dtype: object

In [14]:
df.columns

Index(['country', 'continent', 'year', 'lifeExp', 'pop', 'gdpPercap'], dtype='object')

In [15]:
subset = df[['country', 'continent', 'year']]

In [16]:
print(subset.head())

       country continent  year
0  Afghanistan      Asia  1952
1  Afghanistan      Asia  1957
2  Afghanistan      Asia  1962
3  Afghanistan      Asia  1967
4  Afghanistan      Asia  1972

In [17]:
print(subset.tail())

       country continent  year
1699  Zimbabwe    Africa  1987
1700  Zimbabwe    Africa  1992
1701  Zimbabwe    Africa  1997
1702  Zimbabwe    Africa  2002
1703  Zimbabwe    Africa  2007

## loc 속성으로 행 데이터 추출하기

In [18]:
print(df.loc[0])

country      Afghanistan
continent           Asia
year                1952
lifeExp           28.801
pop              8425333
gdpPercap     779.445314
Name: 0, dtype: object

In [19]:
print(df.loc[99])

country      Bangladesh
continent          Asia
year               1967
lifeExp          43.453
pop            62821884
gdpPercap    721.186086
Name: 99, dtype: object

In [20]:
# print(df.loc[-1]) # 인덱스에 없는 값을 사용하면 오류 발생

In [21]:
df.shape

(1704, 6)

In [22]:
number_of_rows = df.shape[0]
last_row_index = number_of_rows - 1

In [23]:
print(df.loc[last_row_index])

country        Zimbabwe
continent        Africa
year               2007
lifeExp          43.487
pop            12311143
gdpPercap    469.709298
Name: 1703, dtype: object

In [24]:
print(df.loc[1703])

country        Zimbabwe
continent        Africa
year               2007
lifeExp          43.487
pop            12311143
gdpPercap    469.709298
Name: 1703, dtype: object

In [25]:
print(df.loc[1702])

country        Zimbabwe
continent        Africa
year               2002
lifeExp          39.989
pop            11926563
gdpPercap    672.038623
Name: 1702, dtype: object

In [26]:
print(df.tail(n=1))

       country continent  year  lifeExp       pop   gdpPercap
1703  Zimbabwe    Africa  2007   43.487  12311143  469.709298

In [27]:
print(df.loc[ [0, 99, 999] ] )

         country continent  year  lifeExp       pop    gdpPercap
0    Afghanistan      Asia  1952   28.801   8425333   779.445314
99    Bangladesh      Asia  1967   43.453  62821884   721.186086
999     Mongolia      Asia  1967   51.253   1149500  1226.041130

In [28]:
subset_loc = df.loc[0]
subset_tail = df.tail(n=1)

In [29]:
print(type(subset_loc))
print(type(subset_tail))

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>

In [30]:
subset_loc

country      Afghanistan
continent           Asia
year                1952
lifeExp           28.801
pop              8425333
gdpPercap     779.445314
Name: 0, dtype: object

In [31]:
subset_tail

       country continent  year  lifeExp       pop   gdpPercap
1703  Zimbabwe    Africa  2007   43.487  12311143  469.709298

## iloc 속성으로 행 데이터 추출하기

In [32]:
print(df.iloc[1])

country      Afghanistan
continent           Asia
year                1957
lifeExp           30.332
pop              9240934
gdpPercap      820.85303
Name: 1, dtype: object

In [33]:
print(df.loc[1])

country      Afghanistan
continent           Asia
year                1957
lifeExp           30.332
pop              9240934
gdpPercap      820.85303
Name: 1, dtype: object

In [34]:
print(df.iloc[99])

country      Bangladesh
continent          Asia
year               1967
lifeExp          43.453
pop            62821884
gdpPercap    721.186086
Name: 99, dtype: object

In [35]:
print(df.iloc[-1])

country        Zimbabwe
continent        Africa
year               2007
lifeExp          43.487
pop            12311143
gdpPercap    469.709298
Name: 1703, dtype: object

In [36]:
print(df.iloc[ [ 0, 99, 999] ] )

         country continent  year  lifeExp       pop    gdpPercap
0    Afghanistan      Asia  1952   28.801   8425333   779.445314
99    Bangladesh      Asia  1967   43.453  62821884   721.186086
999     Mongolia      Asia  1967   51.253   1149500  1226.041130

## 데이터 추출하기 - 슬라이싱 구문, range 메서드

### (1)  슬라이싱 구문으로 데이터 추출하기

In [37]:
subset = df.loc[:, ['year', 'pop'] ] 
print(subset.head() )

   year       pop
0  1952   8425333
1  1957   9240934
2  1962  10267083
3  1967  11537966
4  1972  13079460

In [38]:
subset = df.iloc[ : , [2, 4, -1] ]
print(subset.head())

   year       pop   gdpPercap
0  1952   8425333  779.445314
1  1957   9240934  820.853030
2  1962  10267083  853.100710
3  1967  11537966  836.197138
4  1972  13079460  739.981106

### (2) range 메서드로 데이터 추출하기

In [39]:
small_range = list(range(5))
print(small_range)

[0, 1, 2, 3, 4]

In [40]:
print(type(small_range))

<class 'list'>

In [41]:
subset = df.iloc[ : , small_range]

In [42]:
print(subset.head())

       country continent  year  lifeExp       pop
0  Afghanistan      Asia  1952   28.801   8425333
1  Afghanistan      Asia  1957   30.332   9240934
2  Afghanistan      Asia  1962   31.997  10267083
3  Afghanistan      Asia  1967   34.020  11537966
4  Afghanistan      Asia  1972   36.088  13079460

In [43]:
small_range = list(range(3,6))
print(small_range)

[3, 4, 5]

In [44]:
df.columns

Index(['country', 'continent', 'year', 'lifeExp', 'pop', 'gdpPercap'], dtype='object')

In [45]:
len(df.columns)

6

In [46]:
for i in range(len(df.columns)):
    print(i, df.columns[i], sep='\t')

0	country
1	continent
2	year
3	lifeExp
4	pop
5	gdpPercap

In [47]:
subset = df.iloc[:, small_range]
print(subset.head())

   lifeExp       pop   gdpPercap
0   28.801   8425333  779.445314
1   30.332   9240934  820.853030
2   31.997  10267083  853.100710
3   34.020  11537966  836.197138
4   36.088  13079460  739.981106

In [48]:
small_range =  list(range(0, 6, 2))
subset = df.iloc[: , small_range]
print(subset.head())

       country  year       pop
0  Afghanistan  1952   8425333
1  Afghanistan  1957   9240934
2  Afghanistan  1962  10267083
3  Afghanistan  1967  11537966
4  Afghanistan  1972  13079460

### (4) 슬라이싱 구문과 range 매서드 비교하기

In [49]:
subset = df.iloc[:, :3]
print(subset.head())

       country continent  year
0  Afghanistan      Asia  1952
1  Afghanistan      Asia  1957
2  Afghanistan      Asia  1962
3  Afghanistan      Asia  1967
4  Afghanistan      Asia  1972

In [50]:
subset = df.iloc[:, : : 2]

In [51]:
subset.head()

       country  year       pop
0  Afghanistan  1952   8425333
1  Afghanistan  1957   9240934
2  Afghanistan  1962  10267083
3  Afghanistan  1967  11537966
4  Afghanistan  1972  13079460

### loc, iloc속성 자유자재로 사용하기

In [52]:
print(df.iloc[ [0, 99, 999] , [0, 3, 5]] )

         country  lifeExp    gdpPercap
0    Afghanistan   28.801   779.445314
99    Bangladesh   43.453   721.186086
999     Mongolia   51.253  1226.041130

In [53]:
# print(df.iloc[ [0, 99, 999] , ['country', 'lifeExp'] ] )

<img src="https://slid-users-assets-v1-seoul.s3.ap-northeast-2.amazonaws.com/public/image_upload/e7ec0583b3904f57a348a10cbcbc680d/aeefe4b6-6b01-4492-bb69-80a3195bab79.png" alt="img" >  
<!--  (1) 크기조절 : ★height="00px" width="00px"★   (2)정렬 : ★align="right"★ -->

In [54]:
print(df.loc[[0, 99, 999], ['country', 'lifeExp', 'gdpPercap']])

         country  lifeExp    gdpPercap
0    Afghanistan   28.801   779.445314
99    Bangladesh   43.453   721.186086
999     Mongolia   51.253  1226.041130

In [55]:
print(df.loc[10:13, ['country', 'lifeExp', 'gdpPercap']])

        country  lifeExp    gdpPercap
10  Afghanistan   42.129   726.734055
11  Afghanistan   43.828   974.580338
12      Albania   55.230  1601.056136
13      Albania   59.280  1942.284244

In [56]:
print(df.loc[1:5, ['country', 'lifeExp']])

       country  lifeExp
1  Afghanistan   30.332
2  Afghanistan   31.997
3  Afghanistan   34.020
4  Afghanistan   36.088
5  Afghanistan   38.438

In [57]:
print(df.loc[ 1:5 ] ) # [ ] 하나로 들어가면 integer로 인식?

       country continent  year  lifeExp       pop   gdpPercap
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106
5  Afghanistan      Asia  1977   38.438  14880372  786.113360

In [58]:
print(df.iloc[1:5] )

       country continent  year  lifeExp       pop   gdpPercap
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106

In [59]:
subset = df.loc[ [2,3] ] # 숫자처럼 보였어도 string이였다. 
print(subset.head())

       country continent  year  lifeExp       pop   gdpPercap
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138

In [60]:
print(df[ ['country', 'year'] ] )

          country  year
0     Afghanistan  1952
1     Afghanistan  1957
2     Afghanistan  1962
3     Afghanistan  1967
4     Afghanistan  1972
...           ...   ...
1699     Zimbabwe  1987
1700     Zimbabwe  1992
1701     Zimbabwe  1997
1702     Zimbabwe  2002
1703     Zimbabwe  2007

[1704 rows x 2 columns]

In [61]:
df.iloc[1:4]

       country continent  year  lifeExp       pop   gdpPercap
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138

In [62]:
df.loc[1:4]

       country continent  year  lifeExp       pop   gdpPercap
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106

### 기타

In [63]:
df2 = pd.DataFrame(
    { "bid_id": [1, 2, 3], 
     "bidder_id": ["Gadi", "Conda", "Lion"], 
     "city": ["Seoul", "LA", "Sydney"], 
     "item": ["TV", "jewelry", "book"]}).set_index("bid_id") 

df2

       bidder_id    city     item
bid_id
1           Gadi   Seoul       TV
2          Conda      LA  jewelry
3           Lion  Sydney     book

In [64]:
df3 = pd.DataFrame(
    { "bid_id": [1, 2, 3], 
     "bidder_id": ["Gadi", "Conda", "Lion"], 
     "city": ["Seoul", "LA", "Sydney"], 
     "item": ["TV", "jewelry", "book"]})
df3

   bid_id bidder_id    city     item
0       1      Gadi   Seoul       TV
1       2     Conda      LA  jewelry
2       3      Lion  Sydney     book

## 02-3 기초적인 통계 계산하기

In [65]:
print(df.head(n=10))

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106
5  Afghanistan      Asia  1977   38.438  14880372  786.113360
6  Afghanistan      Asia  1982   39.854  12881816  978.011439
7  Afghanistan      Asia  1987   40.822  13867957  852.395945
8  Afghanistan      Asia  1992   41.674  16317921  649.341395
9  Afghanistan      Asia  1997   41.763  22227415  635.341351

In [68]:
print(df.groupby('year').mean())

        lifeExp           pop     gdpPercap
year
1952  49.057620  1.695040e+07   3725.276046
1957  51.507401  1.876341e+07   4299.408345
1962  53.609249  2.042101e+07   4725.812342
1967  55.678290  2.265830e+07   5483.653047
1972  57.647386  2.518998e+07   6770.082815
1977  59.570157  2.767638e+07   7313.166421
1982  61.533197  3.020730e+07   7518.901673
1987  63.212613  3.303857e+07   7900.920218
1992  64.160338  3.599092e+07   8158.608521
1997  65.014676  3.883947e+07   9090.175363
2002  65.694923  4.145759e+07   9917.848365
2007  67.007423  4.402122e+07  11680.071820